---


- name: remove existing directory for deployment
  shell: |
    rm -r ~/backend
    mkdir ~/backend

- name: Copy backend sources
  copy:
    src: "artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: extract files
  shell: |
    tar xfz artifact.tar.gz --directory ~/backend

- name: Executing node
  shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 start npm -- start
