---

- name: "Creates backend app directory"
  file:
    path: ~/backend
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Installing Node Dependencies"
  become: true
  apt: 
    name: ["nodejs", "npm"]
    state: present
    update_cache: yes

- name: "Executing Node app with PM2"
  become: true
  shell: |
    cd ~/backend
    npm i
    pm2 stop default
    pm2 start npm -- start
  register: exe_node_app

# - name: "Installing Node Dependencies"
#   become: true
#   shell: |
#     cd ~/backend
#     npm i

# - name: "Executing Node app with PM2"
#   become: true
#   shell: |
#     cd ~/backend
#     pm2 stop default
#     #pm2 start main.js
#     pm2 start npm -- start
#   register: exe_node_app

# - name: "Configure pm2 to start as service"
#   shell: |
#     sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
#     pm2 save

- name: log Executing node
  debug:
    msg: "{{ exe_node_app.stdout_lines }}"
